<?php

namespace NotationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItechsupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItechsupRepository extends EntityRepository
{
}
